[package]
name = "package-manager"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
hex.workspace = true
near-sdk.workspace = true
semver.workspace = true

[dev-dependencies]
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
