[package]
name = "mero-abi"
description = "CLI tool for extracting Calimero WASM ABI"
# Note: workspace versioning doesn't work for tools if published to crates.io, must be independently managed
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
wasmparser = "0.118"
serde_json.workspace = true
eyre.workspace = true
calimero-wasm-abi = { workspace = true }
 
