[package]
name = "cargo-mero"
version.workspace = true
description = "CLI tool for building applications on the Calimero network"
categories = ["command-line-utilities"]
keywords = ["cli", "cargo", "subcommand"]
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
cargo_metadata.workspace = true
clap = { workspace = true, features = ["derive"] }
const_format.workspace = true
eyre.workspace = true
rust-embed.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "io-util"] }

[package.metadata.workspaces]
independent = true

[lints]
workspace = true
