[package]
name = "calimero-node-primitives"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
actix.workspace = true
async-stream.workspace = true
borsh.workspace = true
camino.workspace = true
eyre.workspace = true
futures-util.workspace = true
infer.workspace = true
libp2p = { workspace = true, features = ["gossipsub"] }
rand.workspace = true
reqwest = { workspace = true, features = ["stream"] }
tokio = { workspace = true, features = ["sync"] }
tokio-util.workspace = true
tracing.workspace = true

calimero-crypto.workspace = true
calimero-primitives.workspace = true
calimero-blobstore.workspace = true
calimero-network-primitives.workspace = true
calimero-store.workspace = true
calimero-utils-actix.workspace = true

[lints]
workspace = true
