[package]
name = "calimero-network-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
publish = true

[dependencies]
actix.workspace = true
async-trait.workspace = true
borsh = { workspace = true, features = ["derive"] }
bytes.workspace = true
either.workspace = true
eyre.workspace = true
futures-util.workspace = true
libp2p = { workspace = true, features = ["autonat", "gossipsub", "rendezvous", "request-response"] }
multiaddr.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["compat"] }
tracing.workspace = true

calimero-primitives = { workspace = true, features = ["borsh"] }
calimero-utils-actix.workspace = true

[dev-dependencies]
libp2p = { workspace = true, features = ["autonat", "identify", "macros", "tcp", "tokio", "noise", "yamux"] }
libp2p-swarm-test.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-test.workspace = true
