[package]
name = "calimero-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Abstract client library for Calimero API interactions"

[dependencies]
eyre.workspace = true
url = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["full"] }
thiserror.workspace = true
async-trait = "0.1"
chrono = { workspace = true, features = ["serde"] }
hex.workspace = true
once_cell.workspace = true
webbrowser.workspace = true

# Calimero primitives
calimero-primitives.workspace = true
calimero-server-primitives.workspace = true
calimero-context-config.workspace = true

[dev-dependencies]
tokio-test.workspace = true

[features]
default = []
full = ["reqwest/rustls-tls", "reqwest/gzip", "reqwest/brotli"]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]