[package]
name = "calimero-storage-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
borsh.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild.workspace = true
calimero-sdk.workspace = true
calimero-storage.workspace = true

[lints]
workspace = true
