[package]
name = "mock_ledger"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
ic-cdk = "0.16"
ic-cdk-macros = "0.16"