[package]
name = "calimero-primitives"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bs58.workspace = true
ed25519-dalek.workspace = true
libp2p = { workspace = true, features = ["serde"] }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
hex.workspace = true
