[package]
name = "calimero-primitives"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bs58.workspace = true
borsh = { workspace = true, features = ["derive"], optional = true }
ed25519-dalek.workspace = true
eyre.workspace = true
multiaddr.workspace = true
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
