[package]
name = "calimero-sdk"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
publish = true

[dependencies]
borsh = { workspace = true, features = ["derive"] }
bs58.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
calimero-sdk-macros.workspace = true
calimero-sys.workspace = true
calimero-wasm-abi.workspace = true

[dev-dependencies]
trybuild.workspace = true

[lints]
workspace = true
