[package]
name = "nested-crdt-test"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
calimero-sdk.workspace = true
calimero-storage.workspace = true

[build-dependencies]
calimero-wasm-abi.workspace = true
serde_json.workspace = true
