[package]
name = "calimero-server-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
publish = true

[dependencies]
camino = { workspace = true, features = ["serde1"] }
eyre.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tdx-quote.workspace = true
url = { workspace = true, features = ["serde"] }

calimero-context-config.workspace = true
calimero-context-primitives.workspace = true
calimero-primitives.workspace = true
