[package]
name = "mero-relayer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false
description = "Calimero relayer for external client interactions"

[[bin]]
name = "mero-relayer"
path = "src/main.rs"

[dependencies]
axum.workspace = true
calimero-context-config = { workspace = true, features = ["client"] }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["env", "derive"] }
color-eyre.workspace = true
eyre.workspace = true
futures-util.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["io-std", "macros", "fs", "net", "rt-multi-thread"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true, features = ["serde"] }

[package.metadata.workspaces]
independent = true
