[package]
name = "calimero-crypto"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
publish = true

[dependencies]
curve25519-dalek.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
ring.workspace = true

calimero-primitives = { workspace = true, features = ["rand"] }

[dev-dependencies]
eyre.workspace = true
rand.workspace = true

[lints]
workspace = true
