name: Build and Commit node-ui

on:
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    branches:
      - master
    paths:
      - 'node-ui/**'
  pull_request:
    types:
      - closed

jobs:
  build_node_ui:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check if there are changes in the node-ui folder (excluding build)
      - name: Check for changes in node-ui (excluding build folder)
        id: check_changes
        run: |
          echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          
          git fetch --unshallow || true

          # Check for changes in the node-ui folder (excluding the build directory)
          changes=$(git diff --name-only HEAD~1 HEAD -- 'node-ui' ':!node-ui/build')

          if [ -n "$changes" ]; then
            echo "Changes detected in node-ui."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "No changes in node-ui (excluding build folder)."
          fi

      # Conditional steps, executed only if changes were detected
      - name: Set up Node.js
        if: env.CHANGES_DETECTED == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: npm install -g pnpm

      - name: Install frontend dependencies with pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: pnpm install --prefix ./node-ui

      - name: Build node-ui
        if: env.CHANGES_DETECTED == 'true'
        run: pnpm --filter ./node-ui run build

      # Set up Git credentials for committing
      - name: Set up Git user
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Copy build folder to target repo
        if: env.CHANGES_DETECTED == 'true'
        run: |
          cp -r ../node-ui ./

      - name: Add, commit and push changes to target repo
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add .
          git commit -m "Automated push of node-ui build"
          git push https://${{ secrets.PUSH_TOKEN }}@github.com/frdomovic/admin-dashboard.git main
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
