name: Build and Commit node-ui

on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      deploy:
        description: 'Deploy the build to GitHub Pages'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build_node_ui:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event.inputs.deploy == 'false'
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check for changes in the node-ui folder (excluding build)
      - name: Check for changes in node-ui (excluding build folder)
        id: check_changes
        run: |
          # Initialize the flag to false
          echo "CHANGES_DETECTED=false" >> $GITHUB_ENV

          # Check if HEAD^ exists (i.e., there are at least two commits)
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            # If HEAD^ exists, check for changes in the node-ui folder excluding the build directory
            if git diff --quiet HEAD^ HEAD -- 'node-ui' ':!node-ui/build'; then
              echo "No changes in node-ui (excluding build folder)."
            else
              echo "Changes detected in node-ui."
              echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            fi
          else
            # If HEAD^ doesn't exist (only one commit), check for changes in the first commit
            if git diff-tree --no-commit-id --name-only -r HEAD -- 'node-ui' ':!node-ui/build' | grep .; then
              echo "Changes detected in node-ui."
              echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            else
              echo "No changes in node-ui (excluding build folder)."
            fi
          fi
        env:
          CHANGES_DETECTED: ${{ steps.check_changes.outputs.changes_detected }}

      # Conditional steps, executed only if changes were detected
      - name: Set up Node.js
        if: env.CHANGES_DETECTED == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: npm install -g pnpm

      # Install dependencies and build node-ui
      - name: Install frontend dependencies with pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: pnpm install --prefix ./node-ui

      - name: Build node-ui
        if: env.CHANGES_DETECTED == 'true'
        run: pnpm --filter ./node-ui run build

      # Set up Git credentials for committing
      - name: Set up Git user
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Add changes (build folder) and commit
      - name: Add and commit build folder
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add ./node-ui/build
          git commit --no-verify -m "Automated commit of node-ui build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push changes to the repository
      - name: Push changes
        if: env.CHANGES_DETECTED == 'true'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.event.inputs.deploy == 'true' || needs.build_node_ui.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    needs: build_node_ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./node-ui/build

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}