name: Build and Commit node-ui

on:
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    branches:
      - master
    paths:
      - 'node-ui/**'
  pull_request:
    types:
      - closed

jobs:
  build_node_ui:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current directory
        run: |
          echo "Current directory: $PWD"
          ls -la

      # Check if there are changes in the node-ui folder (excluding build)
      - name: Check for changes in node-ui (excluding build folder)
        id: check_changes
        run: |
          echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          
          git fetch --unshallow || true

          # Check for changes in the node-ui folder (excluding the build directory)
          changes=$(git diff --name-only HEAD~1 HEAD -- 'node-ui' ':!node-ui/build')

          if [ -n "$changes" ]; then
            echo "Changes detected in node-ui."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "No changes in node-ui (excluding build folder)."
          fi

      # Conditional steps, executed only if changes were detected
      - name: Set up Node.js
        if: env.CHANGES_DETECTED == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
 
      - name: Install pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: npm install -g pnpm

      - name: Install frontend dependencies with pnpm
        if: env.CHANGES_DETECTED == 'true'
        run: pnpm install --prefix ./node-ui

      # Set up Git credentials for committing
      - name: Set up Git user
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Build node ui and push changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          echo "Current directory before build: $PWD"
          cd ./node-ui
          echo "Directory after cd to node-ui: $PWD"
          pnpm build
          echo "Directory after build: $PWD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone target repository
        if: env.CHANGES_DETECTED == 'true'
        run: |
          echo "Current directory before cloning: $PWD"
          git clone https://github.com/calimero-network/admin-dashboard.git
          echo "Contents of current directory after cloning:"
          ls -la

      - name: Copy entire node-ui to target repo
        if: env.CHANGES_DETECTED == 'true'
        run: |
          cp -r ./node-ui/* ./admin-dashboard/
          echo "Contents of admin-dashboard after copy:"
          ls -la ./admin-dashboard

      - name: Add, commit and push changes to target repo
        if: env.CHANGES_DETECTED == 'true'
        run: |
          echo "Current directory before cd: $PWD"
          cd ./admin-dashboard
          echo "Current directory after cd: $PWD"
          git add -A
          git commit -m "Automated push of node-ui changes"
          git push https://${{ secrets.PUSH_TOKEN }}@github.com/calimero-network/admin-dashboard.git master
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
